enum CommentSort {
    CONTENT
    COLLECTION
}
type Comment {
    id: ID
    sort: CommentSort
    parentId: Int
    parentCommentId: Int
    userId: Int
    content: String
    isSpoiler: Boolean
    heartCount: Int
    createdAt: Date
    updatedAt: Date
}