type Query {
    heartedCount(userId: Int): Int
    heartedCollections(userId: Int, page: Int, size: Int): [Heart]
    heartedComments(userId: Int, page: Int, size: Int): [Heart]
}
type Mutation {
    saveHeart(input: HeartInput): Heart
    deleteHeart(id: ID!): Heart
}
input HeartInput {
    collectionId: Int
    commentId: Int
    userId: Int
}
type Heart {
    id: ID
    collectionId: Int
    commentId: Int
    userId: Int
    createdAt: Date
    updatedAt: Date
}