type Query {
    watchContents(category: Category, status: Status, userId: Int, page: Int, size: Int): [Watch!]!
    notInterestedContents(userId: Int, page: Int, size: Int): [Watch!]!
}
type Mutation {
    saveWatch(userId: Int, contentId: Int, status: Status): Watch
    deleteWatch(userId: Int, contentId: Int): Watch
}
type Watch {
    id: ID!
    contentId: Int
    userId: Int
    status: Status
    content: Content
    createdAt: Date
    updatedAt: Date
}
enum Status {
    NONE
    WISH
    WATCHING
}